// https://projectpokemon.org/home/docs/spriteindex_148/3d-models-generation-7-pok%C3%A9mon-r96/
//   {"id":, "url":""}

export default [
  {"id":720, "url":"https://projectpokemon.org/images/normal-sprite/hoopa.gif"},
  {"id":721, "url":"https://projectpokemon.org/images/normal-sprite/volcanion.gif"},
  {"id":722, "url":"https://projectpokemon.org/images/normal-sprite/rowlet.gif"},
  {"id":723, "url":"https://projectpokemon.org/images/normal-sprite/dartrix.gif"},
  {"id":724, "url":"https://projectpokemon.org/images/normal-sprite/decidueye.gif"},
  {"id":725, "url":"https://projectpokemon.org/images/normal-sprite/litten.gif"},
  {"id":726, "url":"https://projectpokemon.org/images/normal-sprite/torracat.gif"},
  {"id":727, "url":"https://projectpokemon.org/images/normal-sprite/incineroar.gif"},
  {"id":728, "url":"https://projectpokemon.org/images/normal-sprite/popplio.gif"},
  {"id":729, "url":"https://projectpokemon.org/images/normal-sprite/brionne.gif"},
  {"id":730, "url":"https://projectpokemon.org/images/normal-sprite/primarina.gif"},
  {"id":731, "url":"https://projectpokemon.org/images/normal-sprite/pikipek.gif"},
  {"id":732, "url":"https://projectpokemon.org/images/normal-sprite/trumbeak.gif"},
  {"id":733, "url":"https://projectpokemon.org/images/normal-sprite/toucannon.gif"},
  {"id":734, "url":"https://projectpokemon.org/images/normal-sprite/yungoos.gif"},
  {"id":735, "url":"https://projectpokemon.org/images/normal-sprite/gumshoos.gif"},
  {"id":736, "url":"https://projectpokemon.org/images/normal-sprite/grubbin.gif"},
  {"id":737, "url":"https://projectpokemon.org/images/normal-sprite/charjabug.gif"},
  {"id":738, "url":"https://projectpokemon.org/images/normal-sprite/vikavolt.gif"},
  {"id":739, "url":"https://projectpokemon.org/images/normal-sprite/crabrawler.gif"},
  {"id":740, "url":"https://projectpokemon.org/images/normal-sprite/crabominable.gif"},
  {"id":741, "url":"https://projectpokemon.org/images/normal-sprite/oricorio.gif"},
  {"id":742, "url":"https://projectpokemon.org/images/normal-sprite/cutiefly.gif"},
  {"id":743, "url":"https://projectpokemon.org/images/normal-sprite/ribombee.gif"},
  {"id":744, "url":"https://projectpokemon.org/images/normal-sprite/rockruff.gif"},
  {"id":745, "url":"https://projectpokemon.org/images/normal-sprite/lycanroc.gif"},
  {"id":746, "url":"https://projectpokemon.org/images/normal-sprite/wishiwashi.gif"},
  {"id":747, "url":"https://projectpokemon.org/images/normal-sprite/mareanie.gif"},
  {"id":748, "url":"https://projectpokemon.org/images/normal-sprite/toxapex.gif"},
  {"id":749, "url":"https://projectpokemon.org/images/normal-sprite/mudbray.gif"},
  {"id":750, "url":"https://projectpokemon.org/images/normal-sprite/mudsdale.gif"}
]