// https://github.com/UedaTakeyuki/PokemonTypeEffectivenessData/blob/master/typeeffectiveness.json
export default 
{
    typename: {
        en:{
				Normal: "NORMAL",
				Fighting: "FIGHTING",
				Poison: "POISON",
				Ground: "GROUND",
				Flying: "FLYING",
				bug: "BUG",
				rock: "ROCK",
				ghost: "GHOST",
				steel: "STEEL",
				fire: "FIRE",
				water: "WATER",
				electric: "ELECTRIC",
				grass: "GRASS",
				ice: "ICE",
				psychic: "PSYCHIC",
				dragon: "DRAGON",
				dark: "DARK",
				fairy: "FAIRY",
        },
        ja:{
				Normal: "ノーマル	",
				Fighting: "かくとう",
				Poison: "どく",
				Ground: "じめん",
				Flying: "ひこう",
				bug: "むし",
				rock: "いわ",
				ghost: "ゴースト",
				steel: "はがね",
				fire: "ほのお",
				water: "みず",
				electric: "でんき",
				grass: "くさ",
				ice: "こおり",
				psychic: "エスパ",
				dragon: "ドラゴン",
				dark: "あく",
				fairy: "フェアリー",
        }
    },
    familyname: {
			Normal: "ノーマル	",
			Fighting: "かくとう",
			Poison: "どく",
			Ground: "じめん",
			Flying: "ひこう",
			bug: "むし",
			rock: "いわ",
			ghost: "ゴースト",
			steel: "はがね",
			fire: "ほのお",
			water: "みず",
			electric: "でんき",
			grass: "くさ",
			ice: "こおり",
			psychic: "エスパ",
			dragon: "ドラゴン",
			dark: "あく",
			fairy: "フェアリー",
	},
	suppereffective: {
			Normal: ["Fighting"],
			Fighting: ["Flying","psychic","fairy"],
			Poison: ["Ground","psychic"],
			Ground: ["water","grass","ice"],
			Flying: ["rock","electric","ice"],
			bug: ["Flying","rock","fire"],
			rock: ["Fighting","Ground","water","grass"],
			ghost: ["ghost","dark"],
			steel: ["Fighting","Ground","steel","fire"],
			fire: ["Ground","rock","water"],
			water: ["electric","grass"],
			electric: ["Ground"],
			grass: ["Poison","Flying","bug","fire","ice"],
			ice: ["Fighting","rock","steel","fire"],
			psychic: ["bug","ghost","dark"],
			dragon: ["ice","dragon","fairy"],
			dark: ["Fighting","bug","fairy"],
			fairy: ["Poison","steel"],
	},
	notveryeffective: {
			Normal: [],
			Fighting: ["bug","rock","dark"],
			Poison: ["Fighting","Poison","bug","grass","fairy"],
			Ground: ["Poison","rock"],
			Flying: ["Fighting","bug","grass"],
			bug: ["Fighting","Ground","grass"],
			rock: ["Normal","Poison","Flying","fire"],
			ghost: ["Poison","bug"],
			steel: ["Normal","Flying","bug","rock","steel","grass","ice","psychic","dragon","fairy"],
			fire: ["bug","steel","fire","grass","ice","fairy"],
			water: ["steel","fire","water","ice"],
			electric: ["Flying","steel","electric"],
			grass: ["Ground","water","electric","grass"],
			ice: ["ice"],
			psychic: ["Fighting","psychic"],
			dragon: ["fire","water","electric","grass"],
			dark: ["ghost","dark"],
			fairy: ["Fighting","bug","dark"],
	},
	noeffect: {
			Normal: ["ghost"],
			Fighting: [],
			Poison: [],
			Ground: ["electric"],
			Flying: ["Ground"],
			bug: [],
			rock: [],
			ghost: ["Normal","Fighting"],
			steel: ["Poison"],
			fire: [],
			water: [],
			electric: [],
			grass: [],
			ice: [],
			psychic: [],
			dragon: [],
			dark: ["psychic"],
			fairy: ["dragon"],
	},
	chipscolor: {
			Normal: "mdl-color--gray-400",
			Fighting: "red",
			Poison: "mdl-color--purple-200",
			Ground: "mdl-color--amber-A400",
			Flying: "mdl-color--blue-300",
			bug: "mdl-color--green-A400",
			rock: "mdl-color--orange-300",
			ghost: "mdl-color--deep-purple-400",
			steel: "mdl-color--blue-gray-600",
			fire: "mdl-color--orange-300",
			water: "mdl-color--blue-300",
			electric: "mdl-color--lime-A200",
			grass: "mdl-color--light-green 300",
			ice: "mdl-color--light-blue 100",
			psychic: "mdl-color--purple-A100",
			dragon: "mdl-color--orange-700",
			dark: "mdl-color--indigo-300",
			fairy: "mdl-color--pink-200",
	},
	wording: {
		en:{
				opponent: "Opponent: ",
				select: " (Touch here)",
				chose: "Choose Types",
				supper: "Super-effective!",
				not: "Not very effective!",
				no: "No effect!",
		},
		ja:{
				opponent: "相手は",
				select: "(タッチで切り替え)",
				chose: "相手を選択",
				supper: "効果はばつぐん！",
				not: "効果はいまひとつ！",
				no: "効果がない！",
		}
	}
}